homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 37.3075
  longitude: -121.8963
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 40
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  # Customization file
  customize: !include customize.yaml
    # Add an entry for each entity that you want to overwrite.
    device_tracker.laurensiphone2:
      friendly_name: Lauren
    device_tracker.travissiphone:
      friendly_name: Travis
    media_player.kitchen_home:
      friendly_name: Google Home
    media_player.roku_3_hd:
      friendly_name: Roku
    switch.living_room_light:
      friendly_name: Living Room Lamp
      icon: mdi:lamp
    switch.tv_light:
      friendly_name: TV Lights
      icon: mdi:lamp
    switch.window_light:
      friendly_name: Window Lamp
      icon: mdi:lamp      
    light.lamp_a_10:
      friendly_name: Nightstand
      icon: mdi:lamp      
# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

#access to router and vera
weblink:
    entities:
        - name: Router
          url: http://192.168.1.1
          icon: mdi:router-wireless
        - name: Vera
          url: http://192.168.1.97
          icon: mdi:waves

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
    api_password: "pwd"
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr

# Text to speech
tts:
  - platform: google
#Emulated Hue Bridge
emulated_hue:
  listen_port: 80
# Vera Light
vera:
  vera_controller_url: http://192.168.1.97:3480/
device_tracker:
  - platform: asuswrt
    host: 192.168.1.1
    username: "admin"
    password: "pwd"
    protocol: telnet
    interval_seconds: 20
    consider_home: 120
    track_new_devices: yes
# RF light Switch
switch:
  - platform: rpi_rf
    gpio: 17
    switches:
      tv_light:
        pulselength: 200
        code_on: 1234567
        code_off: 1234568
        signal_repetitions: 15
      window_light:
        pulselength: 200
        code_on: 987654
        code_off: 133742
        signal_repetitions: 15
      living_room_light:
        pulselength: 200
        code_on: 654321,565874,233555,149874
        code_off: 654320,565873,233554,149873
        signal_repetitions: 15
        
# UPS Shipment tracking
sensor:
  - platform: ups
    username: tsc545s
    password: pwd
    update_inverval: '01:00:00'

# USPS Shipment tracking
usps:
    username: tsc545s
    password: pwd

# Fedex Shipment tracking
sensor:
  - platform: fedex
    username: tsc545s
    password: pwd

group: !include groups.yaml
# Example configuration.yaml entry
  default_view:
    view: yes
    icon: mdi:home 
    entities:
      - group.living_room
      - group.bedroom
      - group.kitchen
      - group.family
      - group.climate
      - camera.usps_mail
      - sensor.usps_mail
      - sensor.fedex
      - sensor.remote_a_3
      - sensor.remote_a_4
      - sensor.remote_a_5
      - weblink.router
      - weblink.vera
  living_room:
    name: Living Room
    entities:
      - switch.living_room_light
      - switch.tv_light
      - switch.window_light
      - media_player.roku_3_hd
      - light.lamp_b_11
  bedroom:
    name: Bedroom
    entities:
      - light.lamp_a_10      
  kitchen:
    name: Kitchen
    entities:
      - media_player.kitchen_home
  climate:
    name: Climate
    view: no
    entities:
      - sensor.embedded_humidity_sensor_13
      - sensor.embedded_humidity_sensor_15
      - sensor.embedded_temperature_sensor_12
      - sensor.embedded_temperature_sensor_14
      - sun.sun
  family:
    name: Family
    view: no
    entities:
      - device_tracker.travissiphone
      - device_tracker.laurensiphone2
automation: !include automations.yaml
script: !include scripts.yaml
